servers:
  providers:
    Cloudflare:
    - protocol: DNS
      endpoint: 1.1.1.1
      enabled: true
    - protocol: DNS
      endpoint: 1.0.0.1
      enabled: true
    - protocol: IPv6
      endpoint: 2606:4700:4700::1111
      enabled: true
    - protocol: IPv6
      endpoint: 2606:4700:4700::1001
      enabled: true
    - protocol: DoH
      endpoint: https://cloudflare-dns.com/dns-query
      enabled: false
    - protocol: DoT
      endpoint: cloudflare-dns.com
      enabled: false
    - protocol: DoQ
      endpoint: cloudflare-dns.com
      enabled: true
    Google:
    - protocol: DNS
      endpoint: 8.8.8.8
      enabled: true
    - protocol: DNS
      endpoint: 8.8.4.4
      enabled: true
    - protocol: IPv6
      endpoint: 2001:4860:4860::8888
      enabled: true
    - protocol: IPv6
      endpoint: 2001:4860:4860::8844
      enabled: true
    - protocol: DoH
      endpoint: https://dns.google/dns-query
      enabled: false
    - protocol: DoT
      endpoint: dns.google
      enabled: true
    Quad9:
    - protocol: DNS
      endpoint: 9.9.9.9
      enabled: true
    - protocol: DNS
      endpoint: 149.112.112.112
      enabled: true
    - protocol: IPv6
      endpoint: 2620:fe::fe
      enabled: true
    - protocol: IPv6
      endpoint: 2620:fe::9
      enabled: true
    - protocol: DoH
      endpoint: https://dns.quad9.net/dns-query
      enabled: false
    - protocol: DoT
      endpoint: dns.quad9.net
      enabled: false
    - protocol: DoQ
      endpoint: dns.quad9.net
      enabled: true
    OpenDNS:
    - protocol: DNS
      endpoint: 208.67.222.222
      enabled: true
    - protocol: DNS
      endpoint: 208.67.220.220
      enabled: true
    - protocol: IPv6
      endpoint: 2620:119:35::35
      enabled: true
    - protocol: IPv6
      endpoint: 2620:119:53::53
      enabled: true
    - protocol: DoH
      endpoint: https://doh.opendns.com/dns-query
      enabled: false
    AdGuard DNS:
    - protocol: DNS
      endpoint: 94.140.14.14
      enabled: true
    - protocol: DNS
      endpoint: 94.140.15.15
      enabled: true
    - protocol: IPv6
      endpoint: 2a10:50c0::ad1:ff
      enabled: true
    - protocol: IPv6
      endpoint: 2a10:50c0::ad2:ff
      enabled: true
    - protocol: DoH
      endpoint: https://dns.adguard-dns.com/dns-query
      enabled: false
    - protocol: DoT
      endpoint: dns.adguard-dns.com
      enabled: false
    - protocol: DoQ
      endpoint: dns.adguard-dns.com
      enabled: true
    Control D:
    - protocol: DNS
      endpoint: 76.76.2.0
      enabled: true
    - protocol: DNS
      endpoint: 76.76.10.0
      enabled: true
    - protocol: IPv6
      endpoint: '2606:1a40::'
      enabled: true
    - protocol: IPv6
      endpoint: '2606:1a40:1::'
      enabled: true
    - protocol: DoT
      endpoint: p2.freedns.controld.com
      enabled: true
    CleanBrowsing:
    - protocol: DNS
      endpoint: 185.228.168.9
      enabled: true
    - protocol: DNS
      endpoint: 185.228.169.9
      enabled: true
    - protocol: IPv6
      endpoint: 2a0d:2a00:1::2
      enabled: true
    - protocol: IPv6
      endpoint: 2a0d:2a00:2::2
      enabled: true
    - protocol: DoH
      endpoint: https://doh.cleanbrowsing.org/doh/family-filter/
      enabled: false
    - protocol: DoT
      endpoint: family-filter-dns.cleanbrowsing.org
      enabled: true
    Verisign:
    - protocol: DNS
      endpoint: 64.6.64.6
      enabled: true
    - protocol: DNS
      endpoint: 64.6.65.6
      enabled: true
    - protocol: IPv6
      endpoint: 2620:74:1b::1:1
      enabled: true
    - protocol: IPv6
      endpoint: 2620:74:1c::2:2
      enabled: true
    Yandex:
    - protocol: DNS
      endpoint: 77.88.8.8
      enabled: true
    - protocol: DNS
      endpoint: 77.88.8.1
      enabled: true
    - protocol: IPv6
      endpoint: 2a02:6b8::feed:0ff
      enabled: true
    - protocol: IPv6
      endpoint: 2a02:6b8:0:1::feed:0ff
      enabled: true
    - protocol: DoH
      endpoint: https://dns.yandex.ru/dns-query
      enabled: false
    - protocol: DoT
      endpoint: dns.yandex.ru
      enabled: false
    Neustar:
    - protocol: DNS
      endpoint: 156.154.70.1
      enabled: true
    - protocol: DNS
      endpoint: 156.154.71.1
      enabled: true
    - protocol: IPv6
      endpoint: 2610:a1:1018::1
      enabled: true
    - protocol: IPv6
      endpoint: 2610:a1:1019::1
      enabled: true
    Comodo Secure:
    - protocol: DNS
      endpoint: 8.26.56.26
      enabled: true
    - protocol: DNS
      endpoint: 8.20.247.20
      enabled: true
    DNS Australia (SYD):
    - protocol: DNS
      endpoint: 43.229.60.176
      enabled: false
    - protocol: DNS
      endpoint: 43.229.62.192
      enabled: false
    DNS Australia (MEL):
    - protocol: DNS
      endpoint: 45.124.52.17
      enabled: false
    - protocol: DNS
      endpoint: 45.124.53.159
      enabled: false
    DNS Australia (BNE):
    - protocol: DNS
      endpoint: 103.16.128.53
      enabled: false
    - protocol: DNS
      endpoint: 103.230.156.88
      enabled: false
    Cloudflare (BNE):
    - protocol: DNS
      endpoint: 1.0.0.19
      enabled: true
    Cloudflare (MEL):
    - protocol: DNS
      endpoint: 1.0.0.2
      enabled: true
    Telstra (SYD):
    - protocol: DNS
      endpoint: 139.134.5.51
      enabled: true
    Telstra (MEL):
    - protocol: DNS
      endpoint: 203.50.2.71
      enabled: true
    Getflix (PER):
    - protocol: DNS
      endpoint: 45.248.78.99
      enabled: true
    Node1 (PER):
    - protocol: DNS
      endpoint: 103.117.63.67
      enabled: true
    Telstra (PER):
    - protocol: DNS
      endpoint: 1.159.239.33
      enabled: false
    AussieBB (PER):
    - protocol: DNS
      endpoint: 180.150.123.16
      enabled: false
    - protocol: DNS
      endpoint: 180.150.92.196
      enabled: false
    Dodo (PER):
    - protocol: DNS
      endpoint: 116.240.114.185
      enabled: false
    Level3/Lumen:
    - protocol: DNS
      endpoint: 209.244.0.3
      enabled: true
    - protocol: DNS
      endpoint: 209.244.0.4
      enabled: true
    OpenNIC:
    - protocol: DNS
      endpoint: 134.195.4.2
      enabled: true
