servers:
  providers:
    Cloudflare:
    - protocol: DoQ
      endpoint: cloudflare-dns.com
      enabled: false
      expiry: '2026-02-20 10:21:12'
    - protocol: DNS
      endpoint: 1.1.1.1
      enabled: true
    - protocol: DNS
      endpoint: 1.0.0.1
      enabled: true
    - protocol: DNS
      endpoint: 2606:4700:4700::1111
      enabled: true
    - protocol: DNS
      endpoint: 2606:4700:4700::1001
      enabled: true
    - protocol: DoT
      endpoint: 1.1.1.1
      enabled: true
    - protocol: DoT
      endpoint: cloudflare-dns.com
      enabled: false
      expiry: '2026-02-20 10:21:12'
    - protocol: DoH
      endpoint: https://cloudflare-dns.com/dns-query
      enabled: true
    Google:
    - protocol: DNS
      endpoint: 8.8.8.8
      enabled: true
    - protocol: DNS
      endpoint: 8.8.4.4
      enabled: true
    - protocol: DNS
      endpoint: 2001:4860:4860::8888
      enabled: true
    - protocol: DNS
      endpoint: 2001:4860:4860::8844
      enabled: true
    - protocol: DoT
      endpoint: dns.google
      enabled: false
      expiry: '2026-02-20 10:21:12'
    - protocol: DoH
      endpoint: https://dns.google/dns-query
      enabled: true
    Quad9:
    - protocol: DoQ
      endpoint: dns.quad9.net
      enabled: false
      expiry: '2026-02-20 10:21:12'
    - protocol: DNS
      endpoint: 9.9.9.9
      enabled: true
    - protocol: DNS
      endpoint: 149.112.112.112
      enabled: true
    - protocol: DNS
      endpoint: 2620:fe::fe
      enabled: true
    - protocol: DNS
      endpoint: 2620:fe::9
      enabled: true
    - protocol: DoT
      endpoint: dns.quad9.net
      enabled: false
      expiry: '2026-02-20 10:21:12'
    - protocol: DoH
      endpoint: https://dns.quad9.net/dns-query
      enabled: true
    AdGuard:
    - protocol: DoQ
      endpoint: dns.adguard-dns.com
      enabled: true
    - protocol: DNS
      endpoint: 94.140.14.14
      enabled: true
    - protocol: DNS
      endpoint: 94.140.15.15
      enabled: true
    - protocol: DNS
      endpoint: 2a10:50c0::ad1:ff
      enabled: true
    - protocol: DNS
      endpoint: 2a10:50c0::ad2:ff
      enabled: true
    - protocol: DoT
      endpoint: dns.adguard-dns.com
      enabled: true
    - protocol: DoH
      endpoint: https://dns.adguard-dns.com/dns-query
      enabled: true
    OpenDNS:
    - protocol: DNS
      endpoint: 208.67.222.222
      enabled: true
    - protocol: DNS
      endpoint: 208.67.220.220
      enabled: true
    - protocol: DNS
      endpoint: 2620:119:35::35
      enabled: true
    - protocol: DNS
      endpoint: 2620:119:53::53
      enabled: true
    - protocol: DoH
      endpoint: https://doh.opendns.com/dns-query
      enabled: true
    NextDNS:
    - protocol: DoQ
      endpoint: dns.nextdns.io
      enabled: true
    - protocol: DNS
      endpoint: 45.90.28.0
      enabled: true
    - protocol: DNS
      endpoint: 45.90.30.0
      enabled: true
    - protocol: DNS
      endpoint: '2a07:a8c0::'
      enabled: true
    - protocol: DNS
      endpoint: '2a07:a8c1::'
      enabled: true
    - protocol: DoT
      endpoint: dns.nextdns.io
      enabled: true
    - protocol: DoH
      endpoint: https://dns.nextdns.io
      enabled: true
    ControlD:
    - protocol: DoQ
      endpoint: dns.controld.com
      enabled: true
    - protocol: DNS
      endpoint: 76.76.2.0
      enabled: true
    - protocol: DNS
      endpoint: 76.76.10.0
      enabled: true
    - protocol: DNS
      endpoint: '2606:1a40::'
      enabled: true
    - protocol: DNS
      endpoint: '2606:1a40:1::'
      enabled: true
    - protocol: DoT
      endpoint: dns.controld.com
      enabled: true
    - protocol: DoH
      endpoint: https://dns.controld.com/freedns
      enabled: true
    Mullvad:
    - protocol: DNS
      endpoint: 194.242.2.2
      enabled: true
    - protocol: DNS
      endpoint: 2a07:e340::2
      enabled: true
    - protocol: DoT
      endpoint: dns.mullvad.net
      enabled: false
      expiry: '2026-02-20 10:21:12'
    - protocol: DoH
      endpoint: https://dns.mullvad.net/dns-query
      enabled: true
    CleanBrowsing:
    - protocol: DNS
      endpoint: 185.228.168.9
      enabled: true
    - protocol: DNS
      endpoint: 185.228.169.9
      enabled: true
    - protocol: DNS
      endpoint: 2a0d:2a00:1::2
      enabled: true
    - protocol: DNS
      endpoint: 2a0d:2a00:2::2
      enabled: true
    - protocol: DoT
      endpoint: security-filter-dns.cleanbrowsing.org
      enabled: false
      expiry: '2026-02-20 10:21:12'
    - protocol: DoH
      endpoint: https://doh.cleanbrowsing.org/doh/security-filter/
      enabled: true
    Gcore:
    - protocol: DNS
      endpoint: 95.85.95.85
      enabled: true
    - protocol: DNS
      endpoint: 2.56.192.2
      enabled: false
      expiry: '2026-02-20 10:21:12'
    - protocol: DNS
      endpoint: 2a03:90c0::ad1
      enabled: false
      expiry: '2026-02-20 10:21:12'
    - protocol: DNS
      endpoint: 2a03:90c0::ad2
      enabled: false
      expiry: '2026-02-20 10:21:12'
    UltraDNS:
    - protocol: DNS
      endpoint: 156.154.70.1
      enabled: true
    - protocol: DNS
      endpoint: 156.154.71.1
      enabled: true
    - protocol: DNS
      endpoint: 2610:a1:1018::1
      enabled: true
    - protocol: DNS
      endpoint: 2610:a1:1019::1
      enabled: true
